Revert "Travis should now deploy new tags to PyPI if tests pass"
This reverts commit d39b2e357e34469728f300273ab07c3904ea7a2b.

It failed with this error: https://travis-ci.org/simonw/datasette/jobs/375398977

	Uploading distributions to https://upload.pypi.org/legacy/
	Uploading datasette-0.21-py3-none-any.whl
	100% 182k/182k [00:00<00:00, 694kB/s]
	HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/